version: '3.7'

services:
  backend:
    build:
      context: ./docker-compose/services/backend
      dockerfile: Dockerfile
    ports:
      - 5040:5040
    volumes:
      - ./docker-compose/services/backend:/app
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 5040
  frontend:
    build:
      context: ./docker-compose/services/frontend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./docker-compose/services/frontend:/app



volumes:
    dbdata6:

