version: '3.7'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - ./docker-compose/data/zookeeper/data:/var/lib/zookeeper/data
      - ./docker-compose/data/zookeeper/log:/var/lib/zookeeper/log

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ./docker-compose/data/kafka/data:/var/lib/kafka/data

  spark-master:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '7070:7070'

  spark-worker:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    depends_on:
      - spark-master


  backend:
    build:
      context: ./docker-compose/services/backend
      dockerfile: Dockerfile
    ports:
      - 5040:5040
    volumes:
      - ./docker-compose/services/backend:/app
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 5040
  frontend:
    build:
      context: ./docker-compose/services/frontend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./docker-compose/services/frontend:/app

  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - ./docker-compose/data/dbdata6:/data/db

  postgres:
        container_name: caristock-postgress-db
        image: postgres
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: caristocks
        volumes:
            - ./docker-compose/storage/postgres:/var/lib/postgresql/data
        ports:
            - "5432:5432"

        restart: unless-stopped

volumes:
    dbdata6:

